name: Feature Request
description: "Suggest an idea or new feature."
title: "Feat: "
labels: ["enhancement", "feature"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Give a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's the solution you would like?
      description: Provide a clear and detailed description of what you want to happen and possibly provide a suggested code snippet.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra details
      description: Provide any extra details, screenshots, etc. about the feature request
      
